package rars.assembler;

public enum TokenType {
    OPEN_BRACKET,CLOSE_BRACKET,OFFSET, OFFSET_ADRESS,INSTRUCTION, REGISTER, IMMEDIATE,STRING, DIRECTIVE, LABEL_INIT, COMMENT, ERROR, CONSTANT,LABEL


}
